# Generated by Django 5.1.4 on 2024-12-10 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartitem',
            name='product_id',
        ),
        migrations.AddField(
            model_name='cartitem',
            name='part_number',
            field=models.CharField(default='PN001', max_length=50),
        ),
    ]
